// Auto-generated mock data for testing high load
export const MOCK_USERS = [
  {
    id: "usr-admin-001",
    username: "admin",
    email: "admin@darknero.net",
    role: "super-admin",
    tier: "cloud_managed",
    status: "active",
    bandwidth_quota_gb: 1000,
    bandwidth_used_bytes: 48318382080,
    max_nodes: 10,
    bypass_apps: ["com.apple.Music", "com.spotify.client"]
  },
  {
    id: "usr_alice_01",
    username: "alice",
    email: "alice@company.com",
    role: "user",
    tier: "hybrid_byos",
    status: "active",
    bandwidth_quota_gb: 500,
    bandwidth_used_bytes: 12884901888,
    max_nodes: 5,
    bypass_apps: ["com.spotify.client"]
  },
  {
    id: "usr_bob_02",
    username: "bob_engineer",
    email: "bob@company.com",
    role: "user",
    tier: "cloud_managed",
    status: "active",
    bandwidth_quota_gb: 1000,
    bandwidth_used_bytes: 322122547200,
    max_nodes: 5,
    bypass_apps: []
  },
  {
    id: "usr_carol_03",
    username: "carol_ops",
    email: "carol@company.com",
    role: "user",
    tier: "hybrid_byos",
    status: "active",
    bandwidth_quota_gb: 500,
    bandwidth_used_bytes: 53687091200,
    max_nodes: 5,
    bypass_apps: ["com.netflix.Netflix"]
  }
];

export const MOCK_NODES = [
  {
    "id": "node-exit-001",
    "hostname": "relay-gb-ds1",
    "role": "RELAY",
    "public_ip": "125.242.200.150",
    "mesh_ip": "100.64.0.1",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 10,
    "latency_ms": 44,
    "bandwidth_rx_mb_s": 280.73,
    "bandwidth_tx_mb_s": 65.83,
    "user_id": "system"
  },
  {
    "id": "node-exit-002",
    "hostname": "relay-us-ds4",
    "role": "RELAY",
    "public_ip": "91.238.109.90",
    "mesh_ip": "100.64.0.2",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 20,
    "latency_ms": 20,
    "bandwidth_rx_mb_s": 34.72,
    "bandwidth_tx_mb_s": 28.2,
    "user_id": "system"
  },
  {
    "id": "node-exit-003",
    "hostname": "relay-fr-ds8",
    "role": "RELAY",
    "public_ip": "188.158.11.77",
    "mesh_ip": "100.64.0.3",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 11,
    "latency_ms": 15,
    "bandwidth_rx_mb_s": 339.65,
    "bandwidth_tx_mb_s": 268.78,
    "user_id": "system"
  },
  {
    "id": "node-exit-004",
    "hostname": "relay-us-ds7",
    "role": "RELAY",
    "public_ip": "110.142.24.77",
    "mesh_ip": "100.64.0.4",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 26,
    "bandwidth_rx_mb_s": 254.38,
    "bandwidth_tx_mb_s": 172.12,
    "user_id": "system"
  },
  {
    "id": "node-exit-005",
    "hostname": "relay-de-ds4",
    "role": "RELAY",
    "public_ip": "64.225.2.70",
    "mesh_ip": "100.64.0.5",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 39,
    "bandwidth_rx_mb_s": 397.71,
    "bandwidth_tx_mb_s": 334.36,
    "user_id": "system"
  },
  {
    "id": "node-exit-006",
    "hostname": "relay-fr-ds1",
    "role": "RELAY",
    "public_ip": "70.223.38.115",
    "mesh_ip": "100.64.0.6",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 20,
    "latency_ms": 14,
    "bandwidth_rx_mb_s": 33.11,
    "bandwidth_tx_mb_s": 285.25,
    "user_id": "system"
  },
  {
    "id": "node-exit-007",
    "hostname": "relay-nl-ds6",
    "role": "RELAY",
    "public_ip": "194.189.62.127",
    "mesh_ip": "100.64.0.7",
    "country_code": "NL",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 6,
    "latency_ms": 6,
    "bandwidth_rx_mb_s": 145.35,
    "bandwidth_tx_mb_s": 404.32,
    "user_id": "system"
  },
  {
    "id": "node-exit-008",
    "hostname": "relay-gb-ds8",
    "role": "RELAY",
    "public_ip": "199.65.255.61",
    "mesh_ip": "100.64.0.8",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 15,
    "latency_ms": 36,
    "bandwidth_rx_mb_s": 165.25,
    "bandwidth_tx_mb_s": 221.88,
    "user_id": "system"
  },
  {
    "id": "node-exit-009",
    "hostname": "relay-de-ds5",
    "role": "RELAY",
    "public_ip": "226.120.198.116",
    "mesh_ip": "100.64.0.9",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 28,
    "latency_ms": 47,
    "bandwidth_rx_mb_s": 483.06,
    "bandwidth_tx_mb_s": 17.03,
    "user_id": "system"
  },
  {
    "id": "node-exit-010",
    "hostname": "relay-us-ds6",
    "role": "RELAY",
    "public_ip": "112.159.164.105",
    "mesh_ip": "100.64.0.10",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 27,
    "latency_ms": 16,
    "bandwidth_rx_mb_s": 393.71,
    "bandwidth_tx_mb_s": 130.22,
    "user_id": "system"
  },
  {
    "id": "node-exit-011",
    "hostname": "relay-de-ds4",
    "role": "RELAY",
    "public_ip": "222.236.198.4",
    "mesh_ip": "100.64.0.11",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 25,
    "latency_ms": 8,
    "bandwidth_rx_mb_s": 40.09,
    "bandwidth_tx_mb_s": 191.17,
    "user_id": "system"
  },
  {
    "id": "node-exit-012",
    "hostname": "relay-fr-ds8",
    "role": "RELAY",
    "public_ip": "115.166.101.241",
    "mesh_ip": "100.64.0.12",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 25,
    "latency_ms": 40,
    "bandwidth_rx_mb_s": 233.45,
    "bandwidth_tx_mb_s": 201.8,
    "user_id": "system"
  },
  {
    "id": "node-exit-013",
    "hostname": "relay-de-ds6",
    "role": "RELAY",
    "public_ip": "175.247.222.33",
    "mesh_ip": "100.64.0.13",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 21,
    "latency_ms": 37,
    "bandwidth_rx_mb_s": 168.46,
    "bandwidth_tx_mb_s": 399.8,
    "user_id": "system"
  },
  {
    "id": "node-exit-014",
    "hostname": "relay-ir-ds2",
    "role": "RELAY",
    "public_ip": "108.212.136.226",
    "mesh_ip": "100.64.0.14",
    "country_code": "IR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 28,
    "latency_ms": 14,
    "bandwidth_rx_mb_s": 236.16,
    "bandwidth_tx_mb_s": 91.75,
    "user_id": "system"
  },
  {
    "id": "node-exit-015",
    "hostname": "relay-de-ds2",
    "role": "RELAY",
    "public_ip": "221.155.195.136",
    "mesh_ip": "100.64.0.15",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 3,
    "latency_ms": 5,
    "bandwidth_rx_mb_s": 436.76,
    "bandwidth_tx_mb_s": 20.98,
    "user_id": "system"
  },
  {
    "id": "node-exit-016",
    "hostname": "relay-de-ds4",
    "role": "RELAY",
    "public_ip": "17.185.87.65",
    "mesh_ip": "100.64.0.16",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 29,
    "latency_ms": 8,
    "bandwidth_rx_mb_s": 403.36,
    "bandwidth_tx_mb_s": 457.44,
    "user_id": "system"
  },
  {
    "id": "node-exit-017",
    "hostname": "relay-nl-ds2",
    "role": "RELAY",
    "public_ip": "183.235.164.22",
    "mesh_ip": "100.64.0.17",
    "country_code": "NL",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 25,
    "latency_ms": 50,
    "bandwidth_rx_mb_s": 80.22,
    "bandwidth_tx_mb_s": 204.23,
    "user_id": "system"
  },
  {
    "id": "node-exit-018",
    "hostname": "relay-de-ds4",
    "role": "RELAY",
    "public_ip": "137.232.230.138",
    "mesh_ip": "100.64.0.18",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 12,
    "latency_ms": 34,
    "bandwidth_rx_mb_s": 475.19,
    "bandwidth_tx_mb_s": 252.55,
    "user_id": "system"
  },
  {
    "id": "node-exit-019",
    "hostname": "relay-fr-ds2",
    "role": "RELAY",
    "public_ip": "164.61.213.135",
    "mesh_ip": "100.64.0.19",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 33,
    "bandwidth_rx_mb_s": 123.55,
    "bandwidth_tx_mb_s": 449.7,
    "user_id": "system"
  },
  {
    "id": "node-exit-020",
    "hostname": "relay-ca-ds1",
    "role": "RELAY",
    "public_ip": "48.149.186.40",
    "mesh_ip": "100.64.0.20",
    "country_code": "CA",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 16,
    "latency_ms": 9,
    "bandwidth_rx_mb_s": 81.32,
    "bandwidth_tx_mb_s": 41.64,
    "user_id": "system"
  },
  {
    "id": "node-client-001",
    "hostname": "device-usr-8129",
    "role": "EDGE_CLIENT",
    "public_ip": "204.25.48.107",
    "mesh_ip": "100.64.1.1",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 37,
    "latency_ms": 198,
    "bandwidth_rx_mb_s": 39.87,
    "bandwidth_tx_mb_s": 18.15,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-002",
    "hostname": "device-usr-5135",
    "role": "EDGE_CLIENT",
    "public_ip": "87.226.113.31",
    "mesh_ip": "100.64.1.2",
    "country_code": "US",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 6,
    "latency_ms": 275,
    "bandwidth_rx_mb_s": 22.84,
    "bandwidth_tx_mb_s": 6.49,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-003",
    "hostname": "device-usr-1268",
    "role": "EDGE_CLIENT",
    "public_ip": "229.236.29.18",
    "mesh_ip": "100.64.1.3",
    "country_code": "RU",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 50,
    "latency_ms": 154,
    "bandwidth_rx_mb_s": 47.98,
    "bandwidth_tx_mb_s": 7.71,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-004",
    "hostname": "device-usr-1098",
    "role": "EDGE_CLIENT",
    "public_ip": "39.238.11.246",
    "mesh_ip": "100.64.1.4",
    "country_code": "RU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 7,
    "latency_ms": 118,
    "bandwidth_rx_mb_s": 48.53,
    "bandwidth_tx_mb_s": 16.9,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-005",
    "hostname": "device-usr-7568",
    "role": "EDGE_CLIENT",
    "public_ip": "75.189.78.111",
    "mesh_ip": "100.64.1.5",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 4,
    "latency_ms": 256,
    "bandwidth_rx_mb_s": 45.35,
    "bandwidth_tx_mb_s": 11.19,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-006",
    "hostname": "device-usr-2237",
    "role": "EDGE_CLIENT",
    "public_ip": "171.225.64.164",
    "mesh_ip": "100.64.1.6",
    "country_code": "IN",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 83,
    "latency_ms": 279,
    "bandwidth_rx_mb_s": 31.01,
    "bandwidth_tx_mb_s": 18.49,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-007",
    "hostname": "device-usr-9447",
    "role": "EDGE_CLIENT",
    "public_ip": "188.39.40.32",
    "mesh_ip": "100.64.1.7",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 6,
    "latency_ms": 300,
    "bandwidth_rx_mb_s": 15.08,
    "bandwidth_tx_mb_s": 10.92,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-008",
    "hostname": "device-usr-9574",
    "role": "EDGE_CLIENT",
    "public_ip": "71.46.30.45",
    "mesh_ip": "100.64.1.8",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 16,
    "latency_ms": 21,
    "bandwidth_rx_mb_s": 40.26,
    "bandwidth_tx_mb_s": 6.38,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-009",
    "hostname": "device-usr-4888",
    "role": "EDGE_CLIENT",
    "public_ip": "212.68.119.243",
    "mesh_ip": "100.64.1.9",
    "country_code": "IN",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 98,
    "latency_ms": 22,
    "bandwidth_rx_mb_s": 32.95,
    "bandwidth_tx_mb_s": 10.02,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-010",
    "hostname": "device-usr-5282",
    "role": "EDGE_CLIENT",
    "public_ip": "177.53.154.217",
    "mesh_ip": "100.64.1.10",
    "country_code": "FR",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 99,
    "latency_ms": 150,
    "bandwidth_rx_mb_s": 14.97,
    "bandwidth_tx_mb_s": 18.55,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-011",
    "hostname": "device-usr-6912",
    "role": "EDGE_CLIENT",
    "public_ip": "241.116.116.120",
    "mesh_ip": "100.64.1.11",
    "country_code": "RU",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 36,
    "latency_ms": 185,
    "bandwidth_rx_mb_s": 35.09,
    "bandwidth_tx_mb_s": 12.71,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-012",
    "hostname": "device-usr-6408",
    "role": "EDGE_CLIENT",
    "public_ip": "72.208.129.78",
    "mesh_ip": "100.64.1.12",
    "country_code": "IN",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 63,
    "latency_ms": 213,
    "bandwidth_rx_mb_s": 21.52,
    "bandwidth_tx_mb_s": 8.57,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-013",
    "hostname": "device-usr-3359",
    "role": "EDGE_CLIENT",
    "public_ip": "59.33.41.192",
    "mesh_ip": "100.64.1.13",
    "country_code": "IN",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 92,
    "latency_ms": 232,
    "bandwidth_rx_mb_s": 22.75,
    "bandwidth_tx_mb_s": 10.4,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-014",
    "hostname": "device-usr-9291",
    "role": "EDGE_CLIENT",
    "public_ip": "184.168.42.125",
    "mesh_ip": "100.64.1.14",
    "country_code": "RU",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 97,
    "latency_ms": 253,
    "bandwidth_rx_mb_s": 36.66,
    "bandwidth_tx_mb_s": 9.55,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-015",
    "hostname": "device-usr-3978",
    "role": "EDGE_CLIENT",
    "public_ip": "6.162.7.65",
    "mesh_ip": "100.64.1.15",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 44,
    "latency_ms": 147,
    "bandwidth_rx_mb_s": 5.88,
    "bandwidth_tx_mb_s": 2.45,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-016",
    "hostname": "device-usr-7872",
    "role": "EDGE_CLIENT",
    "public_ip": "46.198.45.223",
    "mesh_ip": "100.64.1.16",
    "country_code": "JP",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 73,
    "bandwidth_rx_mb_s": 24.8,
    "bandwidth_tx_mb_s": 5.44,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-017",
    "hostname": "device-usr-2587",
    "role": "EDGE_CLIENT",
    "public_ip": "73.127.227.134",
    "mesh_ip": "100.64.1.17",
    "country_code": "CA",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 28,
    "latency_ms": 94,
    "bandwidth_rx_mb_s": 40.48,
    "bandwidth_tx_mb_s": 5.9,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-018",
    "hostname": "device-usr-5902",
    "role": "EDGE_CLIENT",
    "public_ip": "117.175.77.32",
    "mesh_ip": "100.64.1.18",
    "country_code": "CA",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 59,
    "latency_ms": 294,
    "bandwidth_rx_mb_s": 14.61,
    "bandwidth_tx_mb_s": 6.31,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-019",
    "hostname": "device-usr-5922",
    "role": "EDGE_CLIENT",
    "public_ip": "119.191.148.22",
    "mesh_ip": "100.64.1.19",
    "country_code": "RU",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 91,
    "latency_ms": 242,
    "bandwidth_rx_mb_s": 21.64,
    "bandwidth_tx_mb_s": 6.63,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-020",
    "hostname": "device-usr-4420",
    "role": "EDGE_CLIENT",
    "public_ip": "114.126.52.88",
    "mesh_ip": "100.64.1.20",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 63,
    "latency_ms": 58,
    "bandwidth_rx_mb_s": 29.14,
    "bandwidth_tx_mb_s": 4.77,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-021",
    "hostname": "device-usr-9772",
    "role": "EDGE_CLIENT",
    "public_ip": "168.14.40.187",
    "mesh_ip": "100.64.1.21",
    "country_code": "CN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 23,
    "latency_ms": 270,
    "bandwidth_rx_mb_s": 7.94,
    "bandwidth_tx_mb_s": 15.44,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-022",
    "hostname": "device-usr-8648",
    "role": "EDGE_CLIENT",
    "public_ip": "133.132.60.170",
    "mesh_ip": "100.64.1.22",
    "country_code": "IN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 63,
    "latency_ms": 124,
    "bandwidth_rx_mb_s": 34.93,
    "bandwidth_tx_mb_s": 18.79,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-023",
    "hostname": "device-usr-9191",
    "role": "EDGE_CLIENT",
    "public_ip": "29.38.122.7",
    "mesh_ip": "100.64.1.23",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 27,
    "bandwidth_rx_mb_s": 12.58,
    "bandwidth_tx_mb_s": 0.11,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-024",
    "hostname": "device-usr-4561",
    "role": "EDGE_CLIENT",
    "public_ip": "108.145.5.234",
    "mesh_ip": "100.64.1.24",
    "country_code": "NL",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 87,
    "latency_ms": 181,
    "bandwidth_rx_mb_s": 33.4,
    "bandwidth_tx_mb_s": 6.5,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-025",
    "hostname": "device-usr-8832",
    "role": "EDGE_CLIENT",
    "public_ip": "196.161.223.12",
    "mesh_ip": "100.64.1.25",
    "country_code": "CH",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 99,
    "latency_ms": 193,
    "bandwidth_rx_mb_s": 28.87,
    "bandwidth_tx_mb_s": 16.31,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-026",
    "hostname": "device-usr-2164",
    "role": "EDGE_CLIENT",
    "public_ip": "62.186.224.224",
    "mesh_ip": "100.64.1.26",
    "country_code": "US",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 6,
    "latency_ms": 34,
    "bandwidth_rx_mb_s": 16.63,
    "bandwidth_tx_mb_s": 14.11,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-027",
    "hostname": "device-usr-4711",
    "role": "EDGE_CLIENT",
    "public_ip": "19.53.169.210",
    "mesh_ip": "100.64.1.27",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 71,
    "latency_ms": 264,
    "bandwidth_rx_mb_s": 49.41,
    "bandwidth_tx_mb_s": 15.78,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-028",
    "hostname": "device-usr-7415",
    "role": "EDGE_CLIENT",
    "public_ip": "109.83.196.26",
    "mesh_ip": "100.64.1.28",
    "country_code": "DE",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 95,
    "latency_ms": 138,
    "bandwidth_rx_mb_s": 6.41,
    "bandwidth_tx_mb_s": 5.1,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-029",
    "hostname": "device-usr-9607",
    "role": "EDGE_CLIENT",
    "public_ip": "227.39.96.226",
    "mesh_ip": "100.64.1.29",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 12,
    "latency_ms": 106,
    "bandwidth_rx_mb_s": 27.67,
    "bandwidth_tx_mb_s": 14.25,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-030",
    "hostname": "device-usr-9473",
    "role": "EDGE_CLIENT",
    "public_ip": "212.16.61.172",
    "mesh_ip": "100.64.1.30",
    "country_code": "KP",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 25,
    "latency_ms": 124,
    "bandwidth_rx_mb_s": 13.85,
    "bandwidth_tx_mb_s": 9.88,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-031",
    "hostname": "device-usr-1511",
    "role": "EDGE_CLIENT",
    "public_ip": "51.1.204.182",
    "mesh_ip": "100.64.1.31",
    "country_code": "CN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 73,
    "latency_ms": 223,
    "bandwidth_rx_mb_s": 20.46,
    "bandwidth_tx_mb_s": 8.4,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-032",
    "hostname": "device-usr-7734",
    "role": "EDGE_CLIENT",
    "public_ip": "93.151.15.156",
    "mesh_ip": "100.64.1.32",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 67,
    "latency_ms": 107,
    "bandwidth_rx_mb_s": 31.03,
    "bandwidth_tx_mb_s": 7.76,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-033",
    "hostname": "device-usr-5306",
    "role": "EDGE_CLIENT",
    "public_ip": "43.166.137.68",
    "mesh_ip": "100.64.1.33",
    "country_code": "CA",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 61,
    "latency_ms": 43,
    "bandwidth_rx_mb_s": 37.2,
    "bandwidth_tx_mb_s": 0.47,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-034",
    "hostname": "device-usr-8227",
    "role": "EDGE_CLIENT",
    "public_ip": "42.197.103.221",
    "mesh_ip": "100.64.1.34",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 52,
    "latency_ms": 83,
    "bandwidth_rx_mb_s": 40.34,
    "bandwidth_tx_mb_s": 8.53,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-035",
    "hostname": "device-usr-9383",
    "role": "EDGE_CLIENT",
    "public_ip": "107.232.43.101",
    "mesh_ip": "100.64.1.35",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 38,
    "latency_ms": 189,
    "bandwidth_rx_mb_s": 9.11,
    "bandwidth_tx_mb_s": 7.24,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-036",
    "hostname": "device-usr-7499",
    "role": "EDGE_CLIENT",
    "public_ip": "231.242.40.78",
    "mesh_ip": "100.64.1.36",
    "country_code": "JP",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 87,
    "latency_ms": 246,
    "bandwidth_rx_mb_s": 49.32,
    "bandwidth_tx_mb_s": 2.55,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-037",
    "hostname": "device-usr-8010",
    "role": "EDGE_CLIENT",
    "public_ip": "186.77.69.16",
    "mesh_ip": "100.64.1.37",
    "country_code": "AU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 27,
    "latency_ms": 30,
    "bandwidth_rx_mb_s": 12.59,
    "bandwidth_tx_mb_s": 4.71,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-038",
    "hostname": "device-usr-5183",
    "role": "EDGE_CLIENT",
    "public_ip": "11.97.239.223",
    "mesh_ip": "100.64.1.38",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 16,
    "latency_ms": 258,
    "bandwidth_rx_mb_s": 4.36,
    "bandwidth_tx_mb_s": 10.29,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-039",
    "hostname": "device-usr-7478",
    "role": "EDGE_CLIENT",
    "public_ip": "97.125.61.51",
    "mesh_ip": "100.64.1.39",
    "country_code": "GB",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 91,
    "latency_ms": 260,
    "bandwidth_rx_mb_s": 20.44,
    "bandwidth_tx_mb_s": 16.38,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-040",
    "hostname": "device-usr-6925",
    "role": "EDGE_CLIENT",
    "public_ip": "195.40.205.215",
    "mesh_ip": "100.64.1.40",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 64,
    "latency_ms": 92,
    "bandwidth_rx_mb_s": 44.61,
    "bandwidth_tx_mb_s": 1.28,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-041",
    "hostname": "device-usr-7538",
    "role": "EDGE_CLIENT",
    "public_ip": "162.170.45.168",
    "mesh_ip": "100.64.1.41",
    "country_code": "RU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 82,
    "latency_ms": 159,
    "bandwidth_rx_mb_s": 5.08,
    "bandwidth_tx_mb_s": 15.71,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-042",
    "hostname": "device-usr-7161",
    "role": "EDGE_CLIENT",
    "public_ip": "58.112.40.210",
    "mesh_ip": "100.64.1.42",
    "country_code": "CH",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 32,
    "latency_ms": 21,
    "bandwidth_rx_mb_s": 6.37,
    "bandwidth_tx_mb_s": 0.42,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-043",
    "hostname": "device-usr-6045",
    "role": "EDGE_CLIENT",
    "public_ip": "6.213.244.89",
    "mesh_ip": "100.64.1.43",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 53,
    "latency_ms": 99,
    "bandwidth_rx_mb_s": 38.65,
    "bandwidth_tx_mb_s": 3.71,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-044",
    "hostname": "device-usr-3154",
    "role": "EDGE_CLIENT",
    "public_ip": "121.9.15.199",
    "mesh_ip": "100.64.1.44",
    "country_code": "NL",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 44,
    "latency_ms": 263,
    "bandwidth_rx_mb_s": 30.76,
    "bandwidth_tx_mb_s": 10.29,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-045",
    "hostname": "device-usr-6956",
    "role": "EDGE_CLIENT",
    "public_ip": "208.107.31.197",
    "mesh_ip": "100.64.1.45",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 84,
    "latency_ms": 93,
    "bandwidth_rx_mb_s": 38.65,
    "bandwidth_tx_mb_s": 4.91,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-046",
    "hostname": "device-usr-6119",
    "role": "EDGE_CLIENT",
    "public_ip": "62.78.5.65",
    "mesh_ip": "100.64.1.46",
    "country_code": "JP",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 6,
    "latency_ms": 113,
    "bandwidth_rx_mb_s": 35.41,
    "bandwidth_tx_mb_s": 17.53,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-047",
    "hostname": "device-usr-6213",
    "role": "EDGE_CLIENT",
    "public_ip": "166.66.146.213",
    "mesh_ip": "100.64.1.47",
    "country_code": "JP",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 87,
    "latency_ms": 43,
    "bandwidth_rx_mb_s": 39.13,
    "bandwidth_tx_mb_s": 1.61,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-048",
    "hostname": "device-usr-6485",
    "role": "EDGE_CLIENT",
    "public_ip": "245.136.128.8",
    "mesh_ip": "100.64.1.48",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 62,
    "latency_ms": 164,
    "bandwidth_rx_mb_s": 15.4,
    "bandwidth_tx_mb_s": 11.28,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-049",
    "hostname": "device-usr-1728",
    "role": "EDGE_CLIENT",
    "public_ip": "1.87.8.214",
    "mesh_ip": "100.64.1.49",
    "country_code": "JP",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 31,
    "latency_ms": 287,
    "bandwidth_rx_mb_s": 33.84,
    "bandwidth_tx_mb_s": 11.17,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-050",
    "hostname": "device-usr-6199",
    "role": "EDGE_CLIENT",
    "public_ip": "231.24.211.181",
    "mesh_ip": "100.64.1.50",
    "country_code": "RU",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 87,
    "latency_ms": 29,
    "bandwidth_rx_mb_s": 8.26,
    "bandwidth_tx_mb_s": 11.08,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-051",
    "hostname": "device-usr-2485",
    "role": "EDGE_CLIENT",
    "public_ip": "133.84.107.109",
    "mesh_ip": "100.64.1.51",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 30,
    "latency_ms": 125,
    "bandwidth_rx_mb_s": 8.71,
    "bandwidth_tx_mb_s": 17.85,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-052",
    "hostname": "device-usr-4237",
    "role": "EDGE_CLIENT",
    "public_ip": "138.32.112.169",
    "mesh_ip": "100.64.1.52",
    "country_code": "RU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 18,
    "latency_ms": 52,
    "bandwidth_rx_mb_s": 0.89,
    "bandwidth_tx_mb_s": 1.28,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-053",
    "hostname": "device-usr-6415",
    "role": "EDGE_CLIENT",
    "public_ip": "41.102.10.45",
    "mesh_ip": "100.64.1.53",
    "country_code": "US",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 9,
    "latency_ms": 203,
    "bandwidth_rx_mb_s": 25.17,
    "bandwidth_tx_mb_s": 3.57,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-054",
    "hostname": "device-usr-2511",
    "role": "EDGE_CLIENT",
    "public_ip": "225.30.67.24",
    "mesh_ip": "100.64.1.54",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 38,
    "latency_ms": 111,
    "bandwidth_rx_mb_s": 8.33,
    "bandwidth_tx_mb_s": 1.69,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-055",
    "hostname": "device-usr-9672",
    "role": "EDGE_CLIENT",
    "public_ip": "43.98.7.83",
    "mesh_ip": "100.64.1.55",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 8,
    "latency_ms": 224,
    "bandwidth_rx_mb_s": 29.1,
    "bandwidth_tx_mb_s": 2.89,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-056",
    "hostname": "device-usr-2735",
    "role": "EDGE_CLIENT",
    "public_ip": "92.28.251.71",
    "mesh_ip": "100.64.1.56",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 52,
    "latency_ms": 123,
    "bandwidth_rx_mb_s": 32.73,
    "bandwidth_tx_mb_s": 8.44,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-057",
    "hostname": "device-usr-9220",
    "role": "EDGE_CLIENT",
    "public_ip": "218.31.126.106",
    "mesh_ip": "100.64.1.57",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 5,
    "latency_ms": 128,
    "bandwidth_rx_mb_s": 39.89,
    "bandwidth_tx_mb_s": 1.48,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-058",
    "hostname": "device-usr-7831",
    "role": "EDGE_CLIENT",
    "public_ip": "30.240.161.131",
    "mesh_ip": "100.64.1.58",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 43,
    "latency_ms": 151,
    "bandwidth_rx_mb_s": 28.31,
    "bandwidth_tx_mb_s": 17.47,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-059",
    "hostname": "device-usr-1919",
    "role": "EDGE_CLIENT",
    "public_ip": "80.67.171.141",
    "mesh_ip": "100.64.1.59",
    "country_code": "IN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 75,
    "latency_ms": 276,
    "bandwidth_rx_mb_s": 35.56,
    "bandwidth_tx_mb_s": 18.0,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-060",
    "hostname": "device-usr-3508",
    "role": "EDGE_CLIENT",
    "public_ip": "200.103.186.17",
    "mesh_ip": "100.64.1.60",
    "country_code": "NL",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 28,
    "latency_ms": 80,
    "bandwidth_rx_mb_s": 5.14,
    "bandwidth_tx_mb_s": 2.89,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-061",
    "hostname": "device-usr-3872",
    "role": "EDGE_CLIENT",
    "public_ip": "184.83.105.219",
    "mesh_ip": "100.64.1.61",
    "country_code": "RU",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 91,
    "latency_ms": 294,
    "bandwidth_rx_mb_s": 46.01,
    "bandwidth_tx_mb_s": 8.77,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-062",
    "hostname": "device-usr-3362",
    "role": "EDGE_CLIENT",
    "public_ip": "152.245.173.28",
    "mesh_ip": "100.64.1.62",
    "country_code": "NL",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 53,
    "latency_ms": 25,
    "bandwidth_rx_mb_s": 18.07,
    "bandwidth_tx_mb_s": 2.3,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-063",
    "hostname": "device-usr-1088",
    "role": "EDGE_CLIENT",
    "public_ip": "114.165.90.36",
    "mesh_ip": "100.64.1.63",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 80,
    "latency_ms": 263,
    "bandwidth_rx_mb_s": 23.96,
    "bandwidth_tx_mb_s": 10.5,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-064",
    "hostname": "device-usr-1638",
    "role": "EDGE_CLIENT",
    "public_ip": "211.22.78.78",
    "mesh_ip": "100.64.1.64",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 62,
    "latency_ms": 205,
    "bandwidth_rx_mb_s": 35.47,
    "bandwidth_tx_mb_s": 19.09,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-065",
    "hostname": "device-usr-2777",
    "role": "EDGE_CLIENT",
    "public_ip": "236.130.245.161",
    "mesh_ip": "100.64.1.65",
    "country_code": "NL",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 96,
    "latency_ms": 267,
    "bandwidth_rx_mb_s": 1.34,
    "bandwidth_tx_mb_s": 13.55,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-066",
    "hostname": "device-usr-1534",
    "role": "EDGE_CLIENT",
    "public_ip": "221.124.120.65",
    "mesh_ip": "100.64.1.66",
    "country_code": "RU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 14,
    "latency_ms": 189,
    "bandwidth_rx_mb_s": 1.12,
    "bandwidth_tx_mb_s": 11.09,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-067",
    "hostname": "device-usr-7840",
    "role": "EDGE_CLIENT",
    "public_ip": "157.206.42.103",
    "mesh_ip": "100.64.1.67",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 58,
    "latency_ms": 279,
    "bandwidth_rx_mb_s": 14.99,
    "bandwidth_tx_mb_s": 13.98,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-068",
    "hostname": "device-usr-1371",
    "role": "EDGE_CLIENT",
    "public_ip": "12.56.78.101",
    "mesh_ip": "100.64.1.68",
    "country_code": "JP",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 78,
    "latency_ms": 247,
    "bandwidth_rx_mb_s": 25.82,
    "bandwidth_tx_mb_s": 8.04,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-069",
    "hostname": "device-usr-3860",
    "role": "EDGE_CLIENT",
    "public_ip": "238.209.39.213",
    "mesh_ip": "100.64.1.69",
    "country_code": "US",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 97,
    "latency_ms": 204,
    "bandwidth_rx_mb_s": 36.43,
    "bandwidth_tx_mb_s": 0.81,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-070",
    "hostname": "device-usr-9851",
    "role": "EDGE_CLIENT",
    "public_ip": "144.223.155.248",
    "mesh_ip": "100.64.1.70",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 60,
    "latency_ms": 156,
    "bandwidth_rx_mb_s": 17.83,
    "bandwidth_tx_mb_s": 15.85,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-071",
    "hostname": "device-usr-9338",
    "role": "EDGE_CLIENT",
    "public_ip": "89.8.124.39",
    "mesh_ip": "100.64.1.71",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 75,
    "latency_ms": 127,
    "bandwidth_rx_mb_s": 11.9,
    "bandwidth_tx_mb_s": 4.57,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-072",
    "hostname": "device-usr-7008",
    "role": "EDGE_CLIENT",
    "public_ip": "175.134.201.50",
    "mesh_ip": "100.64.1.72",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 33,
    "latency_ms": 182,
    "bandwidth_rx_mb_s": 27.51,
    "bandwidth_tx_mb_s": 15.89,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-073",
    "hostname": "device-usr-6378",
    "role": "EDGE_CLIENT",
    "public_ip": "196.35.66.203",
    "mesh_ip": "100.64.1.73",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 72,
    "latency_ms": 80,
    "bandwidth_rx_mb_s": 37.35,
    "bandwidth_tx_mb_s": 5.7,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-074",
    "hostname": "device-usr-3756",
    "role": "EDGE_CLIENT",
    "public_ip": "90.232.192.71",
    "mesh_ip": "100.64.1.74",
    "country_code": "SG",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 59,
    "latency_ms": 66,
    "bandwidth_rx_mb_s": 8.67,
    "bandwidth_tx_mb_s": 15.49,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-075",
    "hostname": "device-usr-8856",
    "role": "EDGE_CLIENT",
    "public_ip": "80.59.110.187",
    "mesh_ip": "100.64.1.75",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 75,
    "latency_ms": 166,
    "bandwidth_rx_mb_s": 21.89,
    "bandwidth_tx_mb_s": 6.52,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-076",
    "hostname": "device-usr-4942",
    "role": "EDGE_CLIENT",
    "public_ip": "82.88.65.226",
    "mesh_ip": "100.64.1.76",
    "country_code": "US",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 59,
    "latency_ms": 20,
    "bandwidth_rx_mb_s": 25.63,
    "bandwidth_tx_mb_s": 10.27,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-077",
    "hostname": "device-usr-8209",
    "role": "EDGE_CLIENT",
    "public_ip": "211.12.218.107",
    "mesh_ip": "100.64.1.77",
    "country_code": "US",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 95,
    "latency_ms": 37,
    "bandwidth_rx_mb_s": 46.39,
    "bandwidth_tx_mb_s": 7.88,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-078",
    "hostname": "device-usr-1162",
    "role": "EDGE_CLIENT",
    "public_ip": "35.216.109.250",
    "mesh_ip": "100.64.1.78",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 35,
    "latency_ms": 83,
    "bandwidth_rx_mb_s": 48.42,
    "bandwidth_tx_mb_s": 7.5,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-079",
    "hostname": "device-usr-9226",
    "role": "EDGE_CLIENT",
    "public_ip": "96.208.104.199",
    "mesh_ip": "100.64.1.79",
    "country_code": "CA",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 50,
    "latency_ms": 170,
    "bandwidth_rx_mb_s": 15.94,
    "bandwidth_tx_mb_s": 3.38,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-080",
    "hostname": "device-usr-3614",
    "role": "EDGE_CLIENT",
    "public_ip": "141.65.132.84",
    "mesh_ip": "100.64.1.80",
    "country_code": "KP",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 80,
    "latency_ms": 256,
    "bandwidth_rx_mb_s": 48.85,
    "bandwidth_tx_mb_s": 16.61,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-081",
    "hostname": "device-usr-2700",
    "role": "EDGE_CLIENT",
    "public_ip": "164.25.210.93",
    "mesh_ip": "100.64.1.81",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 20,
    "latency_ms": 235,
    "bandwidth_rx_mb_s": 8.88,
    "bandwidth_tx_mb_s": 12.68,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-082",
    "hostname": "device-usr-6072",
    "role": "EDGE_CLIENT",
    "public_ip": "170.195.139.172",
    "mesh_ip": "100.64.1.82",
    "country_code": "CN",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 100,
    "latency_ms": 297,
    "bandwidth_rx_mb_s": 14.65,
    "bandwidth_tx_mb_s": 15.95,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-083",
    "hostname": "device-usr-1482",
    "role": "EDGE_CLIENT",
    "public_ip": "93.72.33.3",
    "mesh_ip": "100.64.1.83",
    "country_code": "RU",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 47,
    "latency_ms": 179,
    "bandwidth_rx_mb_s": 25.51,
    "bandwidth_tx_mb_s": 12.81,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-084",
    "hostname": "device-usr-5312",
    "role": "EDGE_CLIENT",
    "public_ip": "140.24.66.242",
    "mesh_ip": "100.64.1.84",
    "country_code": "DE",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 68,
    "latency_ms": 256,
    "bandwidth_rx_mb_s": 34.12,
    "bandwidth_tx_mb_s": 11.5,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-085",
    "hostname": "device-usr-7179",
    "role": "EDGE_CLIENT",
    "public_ip": "172.223.118.249",
    "mesh_ip": "100.64.1.85",
    "country_code": "SE",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 90,
    "latency_ms": 126,
    "bandwidth_rx_mb_s": 48.12,
    "bandwidth_tx_mb_s": 12.26,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-086",
    "hostname": "device-usr-3242",
    "role": "EDGE_CLIENT",
    "public_ip": "47.120.179.65",
    "mesh_ip": "100.64.1.86",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 72,
    "latency_ms": 226,
    "bandwidth_rx_mb_s": 2.85,
    "bandwidth_tx_mb_s": 15.49,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-087",
    "hostname": "device-usr-6130",
    "role": "EDGE_CLIENT",
    "public_ip": "237.233.169.139",
    "mesh_ip": "100.64.1.87",
    "country_code": "GB",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 94,
    "latency_ms": 226,
    "bandwidth_rx_mb_s": 9.71,
    "bandwidth_tx_mb_s": 15.32,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-088",
    "hostname": "device-usr-5323",
    "role": "EDGE_CLIENT",
    "public_ip": "61.248.1.242",
    "mesh_ip": "100.64.1.88",
    "country_code": "CN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 5,
    "latency_ms": 221,
    "bandwidth_rx_mb_s": 36.13,
    "bandwidth_tx_mb_s": 3.68,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-089",
    "hostname": "device-usr-4537",
    "role": "EDGE_CLIENT",
    "public_ip": "159.137.212.134",
    "mesh_ip": "100.64.1.89",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 64,
    "latency_ms": 212,
    "bandwidth_rx_mb_s": 42.13,
    "bandwidth_tx_mb_s": 16.02,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-090",
    "hostname": "device-usr-1514",
    "role": "EDGE_CLIENT",
    "public_ip": "130.124.190.228",
    "mesh_ip": "100.64.1.90",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 82,
    "latency_ms": 41,
    "bandwidth_rx_mb_s": 22.36,
    "bandwidth_tx_mb_s": 13.34,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-091",
    "hostname": "device-usr-5038",
    "role": "EDGE_CLIENT",
    "public_ip": "210.176.70.9",
    "mesh_ip": "100.64.1.91",
    "country_code": "BR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 61,
    "latency_ms": 29,
    "bandwidth_rx_mb_s": 23.96,
    "bandwidth_tx_mb_s": 13.13,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-092",
    "hostname": "device-usr-2181",
    "role": "EDGE_CLIENT",
    "public_ip": "104.235.175.230",
    "mesh_ip": "100.64.1.92",
    "country_code": "IN",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 72,
    "latency_ms": 279,
    "bandwidth_rx_mb_s": 36.31,
    "bandwidth_tx_mb_s": 7.03,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-093",
    "hostname": "device-usr-9511",
    "role": "EDGE_CLIENT",
    "public_ip": "135.88.143.181",
    "mesh_ip": "100.64.1.93",
    "country_code": "CH",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 97,
    "latency_ms": 279,
    "bandwidth_rx_mb_s": 48.08,
    "bandwidth_tx_mb_s": 0.38,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-094",
    "hostname": "device-usr-1574",
    "role": "EDGE_CLIENT",
    "public_ip": "51.186.217.197",
    "mesh_ip": "100.64.1.94",
    "country_code": "GB",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 68,
    "latency_ms": 168,
    "bandwidth_rx_mb_s": 34.67,
    "bandwidth_tx_mb_s": 8.56,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-095",
    "hostname": "device-usr-7277",
    "role": "EDGE_CLIENT",
    "public_ip": "75.182.19.146",
    "mesh_ip": "100.64.1.95",
    "country_code": "SE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 73,
    "latency_ms": 75,
    "bandwidth_rx_mb_s": 17.98,
    "bandwidth_tx_mb_s": 13.8,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-096",
    "hostname": "device-usr-4625",
    "role": "EDGE_CLIENT",
    "public_ip": "201.241.162.145",
    "mesh_ip": "100.64.1.96",
    "country_code": "DE",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 66,
    "latency_ms": 258,
    "bandwidth_rx_mb_s": 19.13,
    "bandwidth_tx_mb_s": 0.88,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-097",
    "hostname": "device-usr-4409",
    "role": "EDGE_CLIENT",
    "public_ip": "237.233.115.154",
    "mesh_ip": "100.64.1.97",
    "country_code": "US",
    "status": "quarantined",
    "is_quarantined": true,
    "risk_score": 93,
    "latency_ms": 276,
    "bandwidth_rx_mb_s": 23.72,
    "bandwidth_tx_mb_s": 13.89,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-098",
    "hostname": "device-usr-7807",
    "role": "EDGE_CLIENT",
    "public_ip": "97.182.76.216",
    "mesh_ip": "100.64.1.98",
    "country_code": "CN",
    "status": "offline",
    "is_quarantined": false,
    "risk_score": 80,
    "latency_ms": 270,
    "bandwidth_rx_mb_s": 10.27,
    "bandwidth_tx_mb_s": 14.28,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-099",
    "hostname": "device-usr-1979",
    "role": "EDGE_CLIENT",
    "public_ip": "197.223.211.189",
    "mesh_ip": "100.64.1.99",
    "country_code": "FR",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 47,
    "latency_ms": 274,
    "bandwidth_rx_mb_s": 33.96,
    "bandwidth_tx_mb_s": 18.8,
    "user_id": "usr-admin-001"
  },
  {
    "id": "node-client-100",
    "hostname": "device-usr-5190",
    "role": "EDGE_CLIENT",
    "public_ip": "40.224.79.223",
    "mesh_ip": "100.64.1.100",
    "country_code": "US",
    "status": "active",
    "is_quarantined": false,
    "risk_score": 24,
    "latency_ms": 133,
    "bandwidth_rx_mb_s": 0.82,
    "bandwidth_tx_mb_s": 11.15,
    "user_id": "usr-admin-001"
  }
];

export const MOCK_APP_BUNDLES = [
  {
    id: "app_guac_01",
    user_id: "usr-admin-001",
    name: "Sovereign Cloud PC (Guacamole)",
    type: "guacamole",
    tier: "cloud_managed",
    status: "running",
    endpoint_url: "https://guac.internal.darknero.net",
    internal_port: 8443,
    cpu_cores: 4.0,
    memory_mb: 8192,
    storage_gb: 200,
    scale_to_zero: 0,
    inactivity_timeout_min: 30,
    last_accessed_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: "app_immich_01",
    user_id: "usr-admin-001",
    name: "Immich Photo Backup",
    type: "immich",
    tier: "cloud_managed",
    status: "running",
    endpoint_url: "https://photos.internal.darknero.net",
    internal_port: 2283,
    cpu_cores: 2.0,
    memory_mb: 4096,
    storage_gb: 500,
    scale_to_zero: 1,
    inactivity_timeout_min: 60,
    last_accessed_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  },
  {
    id: "app_nextcloud_01",
    user_id: "usr_alice_01",
    name: "Nextcloud Sovereign Drive",
    type: "nextcloud",
    tier: "hybrid_byos",
    status: "running",
    endpoint_url: "https://drive.internal.darknero.net",
    internal_port: 8080,
    cpu_cores: 2.0,
    memory_mb: 4096,
    storage_gb: 1000,
    scale_to_zero: 0,
    inactivity_timeout_min: 45,
    last_accessed_at: new Date().toISOString(),
    created_at: new Date().toISOString()
  }
];

export const MOCK_AUDIT_LOGS = [
  {
    id: 1725178900000,
    event_type: "POSTURE_VERIFIED",
    severity: "info",
    actor_user_id: "usr-admin-001",
    actor_username: "admin",
    target_id: "node-exit-001",
    target_type: "node",
    message: "Node 'relay-gb-ds1' completed cryptographic posture verification (Noise_IKpsk2_25519)",
    ip_address: "100.64.0.1",
    user_agent: "NeroNet-Core/4.0.0",
    created_at: new Date(Date.now() - 120000).toISOString()
  },
  {
    id: 1725178800000,
    event_type: "GEO_POLICY_EVAL",
    severity: "info",
    actor_user_id: "system",
    actor_username: "postgis_engine",
    target_id: "country_DE",
    target_type: "policy",
    message: "PostGIS spatial egress boundary evaluation passed for 22 nodes in region DE",
    ip_address: "100.64.0.5",
    user_agent: "PostGIS/3.4",
    created_at: new Date(Date.now() - 300000).toISOString()
  },
  {
    id: 1725178700000,
    event_type: "QUARANTINE_ISOLATION",
    severity: "critical",
    actor_user_id: "system",
    actor_username: "anomaly_daemon",
    target_id: "node-client-095",
    target_type: "node",
    message: "Node 'device-usr-9912' isolated into Zero-Trust quarantine subnet (100.64.250.0/24)",
    ip_address: "100.64.1.95",
    user_agent: "NeroNet-Security/4.0.0",
    created_at: new Date(Date.now() - 600000).toISOString()
  }
];

export const MOCK_TIMESERIES = [
  { time: "00:00", rx: 45.2, tx: 32.1, latency: 14.2 },
  { time: "04:00", rx: 28.6, tx: 19.4, latency: 12.8 },
  { time: "08:00", rx: 78.4, tx: 55.2, latency: 16.5 },
  { time: "12:00", rx: 112.8, tx: 89.4, latency: 18.2 },
  { time: "16:00", rx: 134.5, tx: 98.1, latency: 19.4 },
  { time: "20:00", rx: 95.2, tx: 72.3, latency: 15.6 },
  { time: "24:00", rx: 62.1, tx: 44.8, latency: 14.0 }
];

export const MOCK_GEO_MATRIX = [
  { country: "United States", code: "US", nodes: 28, relays: 4, exits: 6, avg_latency: 18.2, status: "Optimal" },
  { country: "Germany", code: "DE", nodes: 22, relays: 5, exits: 4, avg_latency: 22.4, status: "Optimal" },
  { country: "France", code: "FR", nodes: 15, relays: 3, exits: 2, avg_latency: 19.1, status: "Optimal" },
  { country: "United Kingdom", code: "GB", nodes: 12, relays: 2, exits: 2, avg_latency: 24.6, status: "Optimal" },
  { country: "Netherlands", code: "NL", nodes: 9, relays: 2, exits: 1, avg_latency: 16.8, status: "Optimal" },
  { country: "Canada", code: "CA", nodes: 8, relays: 1, exits: 1, avg_latency: 28.3, status: "Optimal" }
];

export const MOCK_ACL_RULES = [
  {
    id: "acl_001",
    priority: 10,
    source: "100.64.0.0/16",
    destination: "100.64.0.1:53",
    port_proto: "53/UDP",
    action: "ACCEPT",
    description: "Mesh DNS Internal Resolution"
  },
  {
    id: "acl_002",
    priority: 20,
    source: "100.64.250.0/24",
    destination: "100.64.0.0/16",
    port_proto: "*/*",
    action: "DROP",
    description: "Zero-Trust Lateral Quarantine Isolation"
  },
  {
    id: "acl_003",
    priority: 50,
    source: "group:developers",
    destination: "tag:bastion",
    port_proto: "8443/TCP",
    action: "ACCEPT",
    description: "Clientless Guacamole RDP Access"
  }
];

export const MOCK_NERODROP_HISTORY = [
  {
    id: "drop_hist_001",
    file_name: "prod_k8s_manifest_v4.tar.gz",
    file_size_bytes: 4194304,
    source_node_name: "relay-gb-ds1",
    target_node_name: "relay-us-ds4",
    blake3_hash: "3b9a7c4e...8f12",
    status: "completed",
    completed_at: new Date(Date.now() - 3600000).toISOString()
  }
];

export const MOCK_PEERING_AGREEMENTS = [
  {
    id: "peer_ag_001",
    remote_mesh_name: "Frankfurt-DC-Mesh",
    remote_endpoint: "fra-relay.partner-mesh.net:51820",
    remote_public_key: "pKey_FraDC_ed25519_meshPartnerKey991==",
    scope_mode: "ALL",
    shared_subnets: ["100.64.0.0/16", "100.65.0.0/16"],
    shared_devices_count: 24,
    latency_ms: 18.4,
    status: "active",
    expires_at: new Date(Date.now() + 30 * 86400000).toISOString(),
    created_at: new Date().toISOString()
  }
];

export const MOCK_RISK_EVENTS = [
  {
    id: "evt_001",
    type: "IMPOSSIBLE_TRAVEL",
    event_type: "IMPOSSIBLE_TRAVEL",
    severity: "critical",
    node_name: "relay-ir-ds2",
    target_id: "node-exit-014",
    description: "Detected geo-velocity jump 4,200 km/h between Berlin and Tehran within 45s",
    risk_delta: 50,
    timestamp: new Date(Date.now() - 90000).toISOString(),
    created_at: new Date(Date.now() - 90000).toISOString()
  },
  {
    id: "evt_002",
    type: "RTT_DRIFT_ANOMALY",
    event_type: "RTT_DRIFT_ANOMALY",
    severity: "high",
    node_name: "device-usr-5135",
    target_id: "node-client-002",
    description: "Baseline latency drift +255ms with asymmetric packet loss",
    risk_delta: 25,
    timestamp: new Date(Date.now() - 240000).toISOString(),
    created_at: new Date(Date.now() - 240000).toISOString()
  }
];

export const MOCK_GEOFENCING_POLICIES = [
  { country_code: "US", country_name: "United States", action: "ALLOW", node_count: 28, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "DE", country_name: "Germany", action: "ALLOW", node_count: 22, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "GB", country_name: "United Kingdom", action: "ALLOW", node_count: 12, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "FR", country_name: "France", action: "ALLOW", node_count: 15, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "NL", country_name: "Netherlands", action: "ALLOW", node_count: 9, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "CA", country_name: "Canada", action: "ALLOW", node_count: 8, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "CH", country_name: "Switzerland", action: "ALLOW", node_count: 4, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "SE", country_name: "Sweden", action: "ALLOW", node_count: 2, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "JP", country_name: "Japan", action: "ALLOW", node_count: 5, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "SG", country_name: "Singapore", action: "ALLOW", node_count: 3, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "AU", country_name: "Australia", action: "ALLOW", node_count: 2, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "BR", country_name: "Brazil", action: "ALLOW", node_count: 2, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "IN", country_name: "India", action: "ALLOW", node_count: 14, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "RU", country_name: "Russia", action: "QUARANTINE", node_count: 12, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "CN", country_name: "China", action: "ALLOW", node_count: 6, egress_allowed: true, updated_at: new Date().toISOString() },
  { country_code: "IR", country_name: "Iran", action: "QUARANTINE", node_count: 3, egress_allowed: false, updated_at: new Date().toISOString() },
  { country_code: "KP", country_name: "North Korea", action: "BLOCK", node_count: 1, egress_allowed: false, updated_at: new Date().toISOString() }
];

export const MOCK_SOVEREIGN_CLOUD_PC = [
  {
    id: "cpc_001",
    name: "Sovereign Cloud PC (Dev Workstation)",
    webrtc_signaling_url: "wss://workspace.neronet.darknero.com/signaling",
    stun_turn_servers: [{ urls: "stun:stun.l.google.com:19302" }],
    fps: 60,
    resolution: "2560x1440",
    codec: "H264 / AV1",
    status: "active"
  }
];

export const MOCK_CUSTOM_DOMAINS = [
  {
    domain: "workspace.neronet.darknero.com",
    cpc_id: "cpc_001",
    cpc_name: "Sovereign Cloud PC",
    dns_status: "verified",
    ssl_status: "active",
    sso_enforced: true,
    otp_gateway_required: true,
    cname_target: "cpc-ingress.neronet.darknero.com",
    created_at: new Date().toISOString()
  }
];

export const MOCK_NERONUKE_CONFIG = {
  tier1_scheduled_kill: {
    armed: false,
    scheduled_at: null,
    phrase: "DELETE MY ACCOUNT"
  },
  tier1b_personal_dms: {
    armed: true,
    heartbeat_interval_seconds: 2592000,
    last_heartbeat_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    steganography_mode: "shadow_password"
  },
  tier2_owner_dms: {
    armed: false,
    heartbeat_interval_seconds: 604800,
    last_heartbeat_at: new Date().toISOString(),
    webhook_url: "https://matrix.secure.darknero.net/_matrix/hook/canary-alert"
  },
  tier3_warrant_canary: {
    canary_url: "/.well-known/canary.txt",
    last_signed_at: new Date().toISOString(),
    signature_valid: true,
    public_key_fingerprint: "ED25519:9A8B7C6D5E4F3A2B1C0D9E8F7A6B5C4D3E2F1A0B",
    content: "As of 2026, the NeroNet Sovereign Mesh Enterprise Management Console has NOT received any National Security Letters, FISA court orders, secret gag orders, or undisclosed government warrants. All data remains encrypted under sovereign keys."
  }
};
