apiVersion: v1
kind: Service
metadata:
  name: sovereign-relay
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
    service.beta.kubernetes.io/vultr-loadbalancer-region: "nrt"
