apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sovereign.fullname" . }}-secrets
  labels:
    {{- include "sovereign.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-name: {{ .Values.global.clusterName | quote }}
  domain: {{ .Values.global.domain | quote }}
