apiVersion: v1
kind: Service
metadata:
  name: sovereign-relay
  annotations:
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/location: "nbg1"
    load-balancer.hetzner.cloud/use-openapi: "true"
