#!/bin/bash
# =========================================================
# Sovereign Proxy - WireGuard VPN Module (Gaming & Full VPN)
# Installs and configures WireGuard as a Layer 3 tunnel,
# providing native UDP support for gaming, VoIP, and apps
# that cannot use the VLESS proxy (e.g. Among Us, WhatsApp).
# =========================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# -------------------------------------------------------
# Configuration defaults (overridable via config.env)
# -------------------------------------------------------
WG_PORT="${WG_PORT:-443}"
WG_NETWORK="${WG_NETWORK:-10.66.66}"
WG_DNS="${WG_DNS:-1.1.1.1, 8.8.8.8}"
WG_MAX_CLIENTS="${WG_MAX_CLIENTS:-5}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WG_DIR="/etc/wireguard"
CLIENT_DIR="${WG_DIR}/clients"

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}[!] Please run as root${NC}"
    exit 1
fi

# -------------------------------------------------------
# 1. Install WireGuard
# -------------------------------------------------------
echo -e "${GREEN}[*] Installing WireGuard...${NC}"
apt update -qq
apt install -y wireguard wireguard-tools qrencode

# -------------------------------------------------------
# 2. Generate Server Keys
# -------------------------------------------------------
echo -e "${GREEN}[*] Generating server keypair...${NC}"
mkdir -p "$WG_DIR" "$CLIENT_DIR"
chmod 700 "$WG_DIR"

if [ ! -f "${WG_DIR}/server_private.key" ]; then
    wg genkey | tee "${WG_DIR}/server_private.key" | wg pubkey > "${WG_DIR}/server_public.key"
    chmod 600 "${WG_DIR}/server_private.key"
    echo "  Server keys generated."
else
    echo "  Server keys already exist, skipping."
fi

SERVER_PRIVKEY=$(cat "${WG_DIR}/server_private.key")
SERVER_PUBKEY=$(cat "${WG_DIR}/server_public.key")

# -------------------------------------------------------
# 3. Detect Public IP and Network Interface
# -------------------------------------------------------
echo -e "${GREEN}[*] Detecting network configuration...${NC}"
PUBLIC_IP=$(curl -s4 ifconfig.me || curl -s4 icanhazip.com)
NET_IFACE=$(ip -4 route show default | awk '{print $5}' | head -1)

if [ -z "$PUBLIC_IP" ] || [ -z "$NET_IFACE" ]; then
    echo -e "${RED}[!] Failed to detect public IP or network interface.${NC}"
    echo "    PUBLIC_IP=$PUBLIC_IP  NET_IFACE=$NET_IFACE"
    exit 1
fi
echo "  Public IP: $PUBLIC_IP"
echo "  Interface: $NET_IFACE"

# -------------------------------------------------------
# 4. Enable IP Forwarding (persistent)
# -------------------------------------------------------
echo -e "${GREEN}[*] Enabling IP forwarding...${NC}"
if ! grep -q "net.ipv4.ip_forward = 1" /etc/sysctl.d/99-sovereign.conf 2>/dev/null; then
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/99-sovereign.conf
fi
sysctl -w net.ipv4.ip_forward=1

# -------------------------------------------------------
# 5. Create Server Configuration (wg0.conf)
# -------------------------------------------------------
echo -e "${GREEN}[*] Creating WireGuard server configuration...${NC}"
cat > "${WG_DIR}/wg0.conf" << WG_EOF
# =========================================================
# Sovereign Proxy - WireGuard Server (wg0)
# Auto-generated by wireguard.sh — $(date +%Y-%m-%d)
# =========================================================

[Interface]
Address = ${WG_NETWORK}.1/24
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIVKEY}

# NAT: Masquerade outgoing traffic through the public interface
PostUp   = iptables -t nat -A POSTROUTING -s ${WG_NETWORK}.0/24 -o ${NET_IFACE} -j MASQUERADE
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s ${WG_NETWORK}.0/24 -o ${NET_IFACE} -j MASQUERADE
PostDown = iptables -A FORWARD -i wg0 -j ACCEPT
PostDown = iptables -A FORWARD -o wg0 -j ACCEPT

# --- Client Peers ---
# (Added automatically by sovereign-wg-client.sh)
WG_EOF

chmod 600 "${WG_DIR}/wg0.conf"

# -------------------------------------------------------
# 6. Open Firewall Port (UFW + Oracle Security List note)
# -------------------------------------------------------
echo -e "${GREEN}[*] Opening UDP port ${WG_PORT} in UFW...${NC}"
ufw allow "${WG_PORT}/udp" comment 'WireGuard VPN'

echo -e "${YELLOW}    ⚠️  IMPORTANT: You must also add an Ingress Rule in your"
echo -e "    Oracle Cloud Security List for UDP port ${WG_PORT}!"
echo -e "    Networking -> VCN -> Security Lists -> Default Security List"
echo -e "    Protocol: UDP, Source: 0.0.0.0/0, Port: ${WG_PORT}${NC}"

# -------------------------------------------------------
# 7. Enable and Start WireGuard
# -------------------------------------------------------
echo -e "${GREEN}[*] Enabling WireGuard service...${NC}"
systemctl enable wg-quick@wg0
systemctl start wg-quick@wg0 || {
    echo -e "${YELLOW}    WireGuard interface may already be running, restarting...${NC}"
    wg-quick down wg0 2>/dev/null || true
    wg-quick up wg0
}

# -------------------------------------------------------
# 8. Generate First Client Profile
# -------------------------------------------------------
generate_client() {
    local CLIENT_NAME="${1:-phone}"
    local CLIENT_NUM="${2:-2}"
    local CLIENT_IP="${WG_NETWORK}.${CLIENT_NUM}/32"

    echo -e "${GREEN}[*] Generating client profile: ${CLIENT_NAME} (${CLIENT_IP})...${NC}"

    # Generate client keys
    local CLIENT_PRIVKEY=$(wg genkey)
    local CLIENT_PUBKEY=$(echo "$CLIENT_PRIVKEY" | wg pubkey)
    local CLIENT_PSK=$(wg genpsk)

    # Save keys
    mkdir -p "${CLIENT_DIR}/${CLIENT_NAME}"
    echo "$CLIENT_PRIVKEY" > "${CLIENT_DIR}/${CLIENT_NAME}/private.key"
    echo "$CLIENT_PUBKEY"  > "${CLIENT_DIR}/${CLIENT_NAME}/public.key"
    echo "$CLIENT_PSK"     > "${CLIENT_DIR}/${CLIENT_NAME}/preshared.key"
    chmod 600 "${CLIENT_DIR}/${CLIENT_NAME}"/*.key

    # Detect endpoint: prefer DuckDNS domain if available
    local ENDPOINT="$PUBLIC_IP"
    if [ -n "$DUCKDNS_DOMAIN" ] && [ "$DUCKDNS_DOMAIN" != "YOUR-SUBDOMAIN" ]; then
        ENDPOINT="${DUCKDNS_DOMAIN}.duckdns.org"
    fi

    # Create client configuration file
    cat > "${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf" << CLIENT_EOF
# =========================================================
# Sovereign WireGuard - Client: ${CLIENT_NAME}
# Import this file into the WireGuard app on your device.
# =========================================================

[Interface]
Address = ${CLIENT_IP}
PrivateKey = ${CLIENT_PRIVKEY}
DNS = ${WG_DNS}

[Peer]
PublicKey = ${SERVER_PUBKEY}
PresharedKey = ${CLIENT_PSK}
Endpoint = ${ENDPOINT}:${WG_PORT}
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
CLIENT_EOF

    # Add peer to server configuration
    cat >> "${WG_DIR}/wg0.conf" << PEER_EOF

[Peer]  # ${CLIENT_NAME}
PublicKey = ${CLIENT_PUBKEY}
PresharedKey = ${CLIENT_PSK}
AllowedIPs = ${CLIENT_IP}
PEER_EOF

    # Hot-add peer to running interface (no restart needed)
    wg set wg0 peer "$CLIENT_PUBKEY" \
        preshared-key <(echo "$CLIENT_PSK") \
        allowed-ips "${CLIENT_IP}" 2>/dev/null || true

    # Generate QR code for mobile import
    echo ""
    echo -e "${GREEN}  ╔═══════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}  ║   📱 Scan this QR code with the WireGuard app ║${NC}"
    echo -e "${GREEN}  ╚═══════════════════════════════════════════════╝${NC}"
    echo ""
    qrencode -t ANSIUTF8 < "${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf"
    echo ""
    echo -e "${GREEN}  Config file saved to: ${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf${NC}"
    echo ""
}

# Generate default client (phone)
generate_client "phone" 2

# -------------------------------------------------------
# 9. Create Client Management Script
# -------------------------------------------------------
echo -e "${GREEN}[*] Creating client management script...${NC}"
cat > /usr/local/bin/sovereign-wg-client.sh << 'MGMT_EOF'
#!/bin/bash
# =========================================================
# Sovereign WireGuard Client Manager
# Usage: sovereign-wg-client.sh add <name>
#        sovereign-wg-client.sh list
#        sovereign-wg-client.sh qr <name>
#        sovereign-wg-client.sh remove <name>
# =========================================================

WG_DIR="/etc/wireguard"
CLIENT_DIR="${WG_DIR}/clients"

case "$1" in
    add)
        if [ -z "$2" ]; then
            echo "Usage: $0 add <client-name>"
            exit 1
        fi
        # Find next available IP
        LAST_IP=$(grep -oP '10\.66\.66\.\K[0-9]+' "${WG_DIR}/wg0.conf" | sort -n | tail -1)
        NEXT_IP=$((LAST_IP + 1))
        if [ "$NEXT_IP" -gt 254 ]; then
            echo "[!] Maximum clients reached (254)."
            exit 1
        fi
        # Source config.env for DuckDNS domain
        [ -f /opt/sovereign-oci-proxy/config.env ] && source /opt/sovereign-oci-proxy/config.env
        # Re-run the generation function (inline)
        CLIENT_NAME="$2"
        CLIENT_IP="10.66.66.${NEXT_IP}/32"
        CLIENT_PRIVKEY=$(wg genkey)
        CLIENT_PUBKEY=$(echo "$CLIENT_PRIVKEY" | wg pubkey)
        CLIENT_PSK=$(wg genpsk)
        SERVER_PUBKEY=$(cat "${WG_DIR}/server_public.key")
        PUBLIC_IP=$(curl -s4 ifconfig.me)
        ENDPOINT="$PUBLIC_IP"
        WG_PORT=$(grep "^ListenPort" "${WG_DIR}/wg0.conf" | awk '{print $3}')
        if [ -n "$DUCKDNS_DOMAIN" ] && [ "$DUCKDNS_DOMAIN" != "YOUR-SUBDOMAIN" ]; then
            ENDPOINT="${DUCKDNS_DOMAIN}.duckdns.org"
        fi
        mkdir -p "${CLIENT_DIR}/${CLIENT_NAME}"
        echo "$CLIENT_PRIVKEY" > "${CLIENT_DIR}/${CLIENT_NAME}/private.key"
        echo "$CLIENT_PUBKEY"  > "${CLIENT_DIR}/${CLIENT_NAME}/public.key"
        echo "$CLIENT_PSK"     > "${CLIENT_DIR}/${CLIENT_NAME}/preshared.key"
        chmod 600 "${CLIENT_DIR}/${CLIENT_NAME}"/*.key
        cat > "${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf" << EOF
[Interface]
Address = ${CLIENT_IP}
PrivateKey = ${CLIENT_PRIVKEY}
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = ${SERVER_PUBKEY}
PresharedKey = ${CLIENT_PSK}
Endpoint = ${ENDPOINT}:${WG_PORT}
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF
        cat >> "${WG_DIR}/wg0.conf" << EOF

[Peer]  # ${CLIENT_NAME}
PublicKey = ${CLIENT_PUBKEY}
PresharedKey = ${CLIENT_PSK}
AllowedIPs = ${CLIENT_IP}
EOF
        wg set wg0 peer "$CLIENT_PUBKEY" \
            preshared-key <(echo "$CLIENT_PSK") \
            allowed-ips "${CLIENT_IP}" 2>/dev/null || true
        echo "[✅] Client '${CLIENT_NAME}' created with IP ${CLIENT_IP}"
        echo "[📂] Config: ${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf"
        qrencode -t ANSIUTF8 < "${CLIENT_DIR}/${CLIENT_NAME}/${CLIENT_NAME}.conf"
        ;;
    list)
        echo "  ╔═══════════════════════════════════════════╗"
        echo "  ║   Sovereign WireGuard — Active Clients    ║"
        echo "  ╚═══════════════════════════════════════════╝"
        wg show wg0
        echo ""
        echo "  Client profiles:"
        for dir in "${CLIENT_DIR}"/*/; do
            [ -d "$dir" ] && echo "    - $(basename "$dir"): $(grep 'Address' "$dir"/*.conf 2>/dev/null | awk '{print $3}')"
        done
        ;;
    qr)
        if [ -z "$2" ] || [ ! -f "${CLIENT_DIR}/$2/$2.conf" ]; then
            echo "Usage: $0 qr <client-name>"
            echo "Available: $(ls "${CLIENT_DIR}" 2>/dev/null)"
            exit 1
        fi
        qrencode -t ANSIUTF8 < "${CLIENT_DIR}/$2/$2.conf"
        ;;
    remove)
        if [ -z "$2" ]; then
            echo "Usage: $0 remove <client-name>"
            exit 1
        fi
        PUBKEY=$(cat "${CLIENT_DIR}/$2/public.key" 2>/dev/null)
        if [ -n "$PUBKEY" ]; then
            wg set wg0 peer "$PUBKEY" remove
            # Remove peer block from config (between "# $2" marker and next empty line)
            sed -i "/# ${2}$/,/^$/d" "${WG_DIR}/wg0.conf"
            rm -rf "${CLIENT_DIR}/$2"
            echo "[✅] Client '${2}' removed."
        else
            echo "[!] Client '${2}' not found."
        fi
        ;;
    *)
        echo "Sovereign WireGuard Client Manager"
        echo ""
        echo "Usage:"
        echo "  $0 add <name>     Create a new client profile"
        echo "  $0 list           Show all clients and connections"
        echo "  $0 qr <name>     Show QR code for a client"
        echo "  $0 remove <name>  Remove a client"
        ;;
esac
MGMT_EOF

chmod +x /usr/local/bin/sovereign-wg-client.sh

# -------------------------------------------------------
# 10. Final Status
# -------------------------------------------------------
echo ""
echo -e "${GREEN}  ╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}  ║   🛡️  WireGuard VPN Installed Successfully!              ║${NC}"
echo -e "${GREEN}  ╠═══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}  ║   Interface: wg0                                        ║${NC}"
echo -e "${GREEN}  ║   Port:      UDP ${WG_PORT}                                  ║${NC}"
echo -e "${GREEN}  ║   Network:   ${WG_NETWORK}.0/24                            ║${NC}"
echo -e "${GREEN}  ║   Client:    phone (${WG_NETWORK}.2)                       ║${NC}"
echo -e "${GREEN}  ╠═══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}  ║   📱 Scan the QR code above to connect your phone!       ║${NC}"
echo -e "${GREEN}  ║   🎮 Among Us, WhatsApp calls, all UDP apps now work!    ║${NC}"
echo -e "${GREEN}  ╠═══════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}  ║   Manage clients: sovereign-wg-client.sh add <name>     ║${NC}"
echo -e "${GREEN}  ║   Show QR code:   sovereign-wg-client.sh qr <name>      ║${NC}"
echo -e "${GREEN}  ╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}  ⚠️  Don't forget to open UDP ${WG_PORT} in Oracle Cloud Security List!${NC}"
echo ""

wg show wg0
