apiVersion: v1
kind: Service
metadata:
  name: sovereign-relay
  labels:
    app.kubernetes.io/name: sovereign-mesh
    app.kubernetes.io/component: relay
spec:
  type: LoadBalancer
  ports:
    - name: https-derp
      port: 443
      targetPort: 443
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: honeypot
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: sovereign-mesh
    app.kubernetes.io/component: relay
